name: PR Checks

on:
  pull_request:
    branches:
      - dev
      - main
    types:
      - opened
      - edited
      - synchronize

concurrency:
  group: "${{ github.workflow }} @ ${{ github.event.pull_request.head.label || github.head_ref || github.ref }}"
  cancel-in-progress: true

jobs:
  pr-validation:
    name: PR Validation
    uses: UnicoLab/ul_cicd-workflows/.github/workflows/pr-checks.yml@main
    with:
      lint-python: true
      lint-yaml: true
      run-codeql: false
    secrets: inherit
