name: Deploy PR Pages Preview

on:
  push:
    branches-ignore:
      - main
    paths:
      - "docs/**"
      - mkdocs.yml
  pull_request:
    branches:
      - main
    paths:
      - "docs/**"
      - mkdocs.yml
    types:
      - opened
      - reopened
      - edited
      - synchronize

concurrency: preview-${{ github.ref }}

permissions:
  contents: write
  pull-requests: write
  pages: write
  id-token: write

jobs:
  deploy-pr-preview:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Poetry
        uses: UnicoLab/ul_cicd-workflows/.github/actions/setup-poetry@main
        with:
          python-version: "3.11"
          poetry-version: "latest"
          cache-dependencies: true
      
      - name: Install dependencies
        run: poetry install --all-extras --no-interaction

      - name: Build documentation
        run: poetry run mkdocs build

      - name: Deploy preview
        uses: rossjrw/pr-preview-action@v1
        with:
          source-dir: ./site/
          token: ${{ secrets.GITHUB_TOKEN }}
