name: Deploy PR Pages Preview

on:
  push:
    branches-ignore:
      - main
    paths:
      - "docs/**"
      - "mkdocs.yml"
  pull_request:
    branches:
      - main
    paths:
      - "docs/**"
      - "mkdocs.yml"
    types:
      - opened
      - reopened
      - edited
      - synchronize

concurrency: preview-${{ github.ref }}

permissions:
  contents: write
  pull-requests: write
  pages: write
  id-token: write

jobs:
  deploy-pr-preview:
    uses: UnicoLab/ul_cicd-workflows/.github/workflows/pr-preview.yml@main
    with:
      python-versions: '["3.11"]'
      dependencies-manager: 'poetry'
      docs-tool: 'mkdocs'
      source-dir: './site/'
    secrets: inherit
