name: Deploy PR Pages Preview

on:
  push:
    branches:
      - dev
      - main
    paths:
      - "docs/**"
      - mkdocs.yml
  pull_request:
    branches:
      - dev
      - main
    paths:
      - "docs/**"
      - mkdocs.yml
    types:
      - opened
      - reopened
      - edited
      - synchronize

concurrency: preview-${{ github.ref }}

jobs:
  deploy-pr-preview:
    runs-on: ["ubuntu-latest"]
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"
          cache: "pip"

      - name: Install Python dependencies
        shell: bash
        run: |
          python -m pip install --upgrade pip
          # installing poetry
          pip install poetry
          # disable venvs
          poetry config virtualenvs.create false
          # assuring we have all extras for testing as well
          poetry install --all-extras --no-interaction

      - name: Install and Build
        shell: bash
        run: |
          mkdocs build
          echo "DOC GENERATED - OK!"

      - name: Deploy preview
        uses: rossjrw/pr-preview-action@v1
        with:
          source-dir: ./site/
          token: ${{ secrets.GITHUB_TOKEN }}
